stages:
  train:
    cmd: set PYTHONPATH=%CD% && python training/train.py
    deps:
      - training/train.py
      - training/preprocess.py
      - utils/config_loader.py
      - data
    outs:
      - artifacts/rf_pitch_model.joblib
      - artifacts/ohe_encoder.joblib